apiVersion: v1
data:
  JWT_SECRET: c3VwZXJfc2VjcmV0
  MINIO_SECRET_KEY: bWluaW9hZG1pbg==
  POSTGRES_PASSWORD: ZGFtcGFzcw==
  RABBITMQ_PASSWORD: cmFiYml0cGFzcw==
  REDIS_PASSWORD: cmVkaXNwYXNz
kind: Secret
metadata:
  creationTimestamp: "2026-03-12T09:21:29Z"
  name: dam-secrets
  namespace: dam-platform
  resourceVersion: "11683"
  uid: 2f82f937-b992-4367-b45c-e027f5032313
type: Opaque
