apiVersion: v1
kind: Secret
metadata:
  name: dam-secrets
  namespace: dam-platform
type: Opaque
data:
  POSTGRES_PASSWORD: ZGFtcGFzcw==
  REDIS_PASSWORD: cmVkaXNwYXNz
  RABBITMQ_PASSWORD: cmFiYml0cGFzcw==
  MINIO_SECRET_KEY: bWluaW9wYXNz