FROM node:20-alpine
 
WORKDIR /app
 
RUN npm install -g turbo
COPY package.json pnpm-lock.yaml* ./
 
RUN corepack enable && corepack prepare pnpm@latest --activate

RUN pnpm install
 
COPY . .
 
EXPOSE 3002

CMD ["pnpm", "--filter", "upload", "run", "dev"]
