export const MAX_FILES = 20;

export const UI_STRINGS = {
  SIGN_UP_PAGE: {
    SUB_HEADING: "Digital Asset Management",
    CREATE_ACCOUNT: "Create an account",
    GET_STARTED: "Get started — it's free",
    HAVE_ACCOUNT: "Already have an account?",
    AGREE: "By continuing you agree to our",
    TERMS: "Terms of Service",
    PRIVACY: "Privacy Policy",
    AND: "and",
  },
  CREDENTIALS: {
    EMAIL: "Email",
    PASSWORD: "Password",
  },

  LOGIN_PAGE: {
    SUB_HEADING: "Digital Asset Management",
    WELCOME_BACK: "Welcome back",
    SIGN_IN_TO_CONTINUE: "Sign in to continue",
    NO_ACCOUNT: "Don't have an account?",
    FORGOT_PASSWORD: "Forgot password?",
  },
  BUTTONS: {
    CREATE: "Create account",
    SIGN_IN: "Sign in",
    SIGN_UP: "Sign up",
  },
  UPDATE_MODAL: {
    UPLOAD_FILE_TEXT: "Drop files here or click to browse",
    ANY_FILE: `Any file type · Up to ${MAX_FILES} files at once`,
    STATUS: {
      QUEUED: "queued",
      UPLOADING: "uploading",
      DONE: "done",
      ERROR: "error",
    },
    DONE: "Done",
    UPLOADED: "uploaded",
    FAILED: "failed",
    UPLOAD_MORE: "Upload more",
    CLOSE: "Close",
  },

  DELETE_MODAL: {
    DELETE: "Permanently delete this asset?",
    WARNING: "will be removed from storage. This cannot be undone.",
    CANCEL: "Cancel",
    DLT_BUTTON: "Delete",
    DELETING: "Deleting...",
    FAILED: "Failed",
  },
  DETAIL_MODAL: {
    TAGS: "Tags",
    DOWNLOAD: "Download",
    SHARE: "Share",
    DELETE: "Delete",
    NO_PREVIEW: "No preview available",
    PREVIEW_UNAVAILABLE: "Preview unavailable",
    TRANSCODING_IN_PROGRESS: "Transcoding in progress — playing original",
    QUALITY_OPTION: "quality option",
    AVAILABLE: "available",
    LOADING: "Loading…",
    ORIGINAL: "Original",
    FILE: "file",
    TRANSCODED: "Transcoded",
  },
  SHARE_MODAL: {
    HEADING: "Share link created. Copy and send it.",
    COPIED: "Copied!",
    COPY: "Copy link",
    SHARE: "Share",
    OPTIONAL: "All options are optional.",
    EXPIRE: "Expires (hours)",
    DOWNLOADS: "Max downloads",
    PASSWORD: "Password (optional)",
    CANCEL: "Cancel",
    CREATING: "Creating…",
    LINK: "Create link",
  },
  DASHBOARD: {
    UPLOAD: "Upload",
    ASSET: "asset",
    PREVIOUS: "Previous",
    PAGE: "Page",
    OF: "of",
    NEXT: "Next",
    NO_RESULT: "No results",
    SEARCH_TERM: "Try a different search term.",
    NO_ASSETS: "No assets yet",
    FIRST_FILE: "Upload your first file to get started.",
    UPLOAD_FILE: "Upload file",
  },
} as const;
