apiVersion: v1
kind: ConfigMap
metadata:
  name: dam-config
  namespace: dam-platform
data:
  NODE_ENV: "production"

  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "dam_platform"
  POSTGRES_USER: "dam_user"

  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "dam_rabbit"
  RABBITMQ_VHOST: "dam"

  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_BUCKET_CHUNKS: "dam-chunks"
  MINIO_BUCKET_ASSETS: "dam-assets"

  PORT_AUTH: "3001"
  PORT_UPLOAD: "3002"
  PORT_ASSET: "3003"

  FRONTEND_URL: "http://web-service"

  JWT_EXPIRY: "86400"
