FROM node:20-alpine

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml* ./
COPY apps/api/package.json ./apps/api/package.json

RUN pnpm install

EXPOSE 3000 3001 3002 3003

CMD ["pnpm", "--filter", "api", "run", "dev"]